### ISSUE TITLE
Every time you visit a project selector on the backend, it adds a blank filter

### ISSUE THREAD

**Issue by rebbrunner** [bgsu-pal/paclab-www#73]
You can't save the selector until you have filled in this blank filter, essentially entailing you can't edit the selector using the admin site.

**Comment by psybers** [comment]
What are the exact steps to reproduce?

I edit selectors on the back end all the time.  I just tried it and it worked fine for me.

**Comment by rebbrunner** [comment]
Nvm, I think the issue was that I was setting all the filters from Ready to Processed and also set the setting for the blank entry at the bottom, causing an error.
